### ISSUE TITLE
0.16.1使用deferred as打包web报错

### ISSUE THREAD

**Issue by rhgzs** [mpflutter/mpflutter#202]
以下为报错信息

```
Unhandled exception:
FormatException: Unexpected end of input (at character 26)
["main.dart.js_3.part.js"
                         ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#3      JsonDecoder.convert (dart:convert/json.dart:612:36)
#4      JsonCodec.decode (dart:convert/json.dart:216:41)
#5      _addHashToDeferredParts.<anonymous closure> (package:mp_build_tools/build_web.dart:113:26)
#6      _StringBase.replaceAllMapped (dart:core-patch/string_patch.dart:739:35)
#7      _addHashToDeferredParts (package:mp_build_tools/build_web.dart:110:15)
<asynchronous suspension>
#8      _buildDartJS (package:mp_build_tools/build_web.dart:57:3)
<asynchronous suspension>
#9      main (package:mp_build_tools/build_web.dart:14:3)
<asynchronous suspension>
```

**Comment by PonyCui** [comment]
噢，你现在可以试试 0.16.2 了，有一个边界条件没有处理好。

**Comment by rhgzs** [comment]
好嘞
