### ISSUE TITLE
使用http包进行文件上传出现问题

### ISSUE THREAD

**Issue by jijkbird** [mpflutter/mpflutter#397]
```
Uri url = Uri.http('lure-plus.oss-cn-chengdu.aliyuncs.com', '');
    http.MultipartRequest request = http.MultipartRequest('POST', url);
    request.fields['key'] = pathName;
    request.fields['policy'] = getSplicyBase64(policyText);
    request.fields['OSSAccessKeyId'] = ossAccessKeyId; //换成自己的
    request.fields['success_action_status'] = '200';
    request.fields['signature'] = signature;
    http.MultipartFile multipartFile =
        http.MultipartFile.fromBytes("file", await file!.readAsBytes());
    request.files.add(multipartFile);
    http.StreamedResponse response = await request.send();
    print(response.statusCode);
    print(await response.stream.bytesToString());
    print(request.fields);
    if (response.statusCode == 200) {
      return '$myUrl/$pathName';
    }
```

debug版本请求正常，但格式被拒绝
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>MalformedPOSTRequest</Code>
  <Message>The body of your POST request is not well-formed multipart/form-data</Message>
  <RequestId>63FAE63404ACC0303679F516</RequestId>
  <HostId>lure-plus.oss-cn-chengdu.aliyuncs.com</HostId>
  <EC>0006-00000109</EC>
</Error>

release版本 发不出去请求

WAServiceMainContext.js:2 FormatException: Unexpected extension byte (at offset 0)
    at Object.b (http://127.0.0.1:33335/appservice/main.dart.js:999:3)
    at nT.q5 (http://127.0.0.1:33335/appservice/main.dart.js:16808:9)
    at vC.aP (http://127.0.0.1:33335/appservice/main.dart.js:16708:42)
    at vC.p (http://127.0.0.1:33335/appservice/main.dart.js:16707:13)
    at ia.p (http://127.0.0.1:33335/appservice/main.dart.js:16420:15)
    at kc.lf (http://127.0.0.1:33335/appservice/main.dart.js:15078:3)
    at tear_off.<anonymous> (http://127.0.0.1:33335/appservice/main.dart.js:1118:65)
    at v1.eP (http://127.0.0.1:33335/appservice/main.dart.js:15267:21)
    at jN.f9 (http://127.0.0.1:33335/appservice/main.dart.js:14840:5)
    at ib.mR (http://127.0.0.1:33335/appservice/main.dart.js:14917:9)(env: macOS,mp,1.06.2301160; lib: 2.18.0)

**Comment by PonyCui** [comment]
https://github.com/mpflutter/mpflutter/issues/396
