### ISSUE TITLE
另外release包经常性出现白屏，调试台报错bad states,，从分享入口等其他非日常入口进入时出现的频率很大。

### ISSUE THREAD

**Issue by PonyCui** [mpflutter/mpflutter#418]
另外release包经常性出现白屏，调试台报错bad states,，从分享入口等其他非日常入口进入时出现的频率很大。
这个问题就真的很致命了...

白屏时控制台报错：
MiniProgramError
Bad state: No element
at a (app-service.js:3888:13016)
at cn (app-service.js:3888:194894)
at  (app-service.js:3888:447316)
at  (app-service.js:3888:43964)
at $2 (app-service.js:3888:225069)
at r (app-service.js:3888:43640)
at  (app-service.js:3888:143177)
at  (app-service.js:3888:43964)
at $2 (app-service.js:3888:225069)
at r (app-service.js:3888:43640)
at Mz (app-service.js:3888:136315)
at $1 (app-service.js:3888:482047)
at OV (app-service.js:3888:85234)
at  (app-service.js:3894:118532)
at  (app-service.js:3894:146582)
at k (WASubContext.js:1:70041)
at  (app-service.js:3894:146520)
at  (app-service.js:3894:2013)
at  (app-service.js:3894:1044)
at k (WASubContext.js:1:70041)
at __awaiter (app-service.js:3894:804)
at  (app-service.js:3894:135083)
at  (app-service.js:3894:2013)
at s (app-service.js:3894:846)
at Q (WASubContext.js:1:68759)
at  (WASubContext.js:1:68981)
at I (WASubContext.js:1:38458)
at  (WASubContext.js:1:52254)
at x (WASubContext.js:1:52023)
at  (WASubContext.js:1:52061)
at <setTimeout callback function>
at  (WASubContext.js:1:124456)
at  (WASubContext.js:1:154437)
at p (WAServiceMainContext.js:1:158714)
at  (WAServiceMainContext.js:1:146943)
_onNativeTimer@
global code@

_Originally posted by @tripleLBeTaken in https://github.com/mpflutter/mpflutter/issues/417#issuecomment-1480000194_

**Comment by kenny2006cen** [comment]
确实，我也遇到了

**Comment by bigshezhang** [comment]
我也遇到了

**Comment by bigshezhang** [comment]
我这边解决了，问题会发生在冷启动小程序后，通过分享链接再热启动时。
猜测问题：AppHide 的时候会调用 thePage 里的 onUnload，将 element 卸载导致热启动时找不到 element。
解决方法：将 mpdom.min.js 中 `onUnload: function () { this.mpPage.viewId && n.router.disposeRoute(this.mpPage.viewId); },` 的 onUnload 注释即可解决分享白屏问题。

**Comment by whxlxl** [comment]
问题+1，分享进去基本100%出现

**Comment by whxlxl** [comment]
> 我这边解决了，问题会发生在冷启动小程序后，通过分享链接再热启动时。 猜测问题：AppHide 的时候会调用 thePage 里的 onUnload，将 element 卸载导致热启动时找不到 element。 解决方法：将 mpdom.min.js 中 `onUnload: function () { this.mpPage.viewId && n.router.disposeRoute(this.mpPage.viewId); },` 的 onUnload 注释即可解决分享白屏问题。

这种方法虽然可以解决分享后再次进入白屏的问题，但是程序内部的页面跳转后，会出问题，setState 将会无效，页面的数值不在变化。就像一张图片一样。

**Comment by whxlxl** [comment]
> 我这边解决了，问题会发生在冷启动小程序后，通过分享链接再热启动时。 猜测问题：AppHide 的时候会调用 thePage 里的 onUnload，将 element 卸载导致热启动时找不到 element。 解决方法：将 mpdom.min.js 中 `onUnload: function () { this.mpPage.viewId && n.router.disposeRoute(this.mpPage.viewId); },` 的 onUnload 注释即可解决分享白屏问题。

我对这个前端相关的不是很熟悉，我又试了你的方法，发现要自定义appbar 的返回按钮才能完美解决这个问题，如果是微信自带的appbar进行返回，就会出现我上面说的情况（大概意思就是，小程序全程的所有页面切换必须经过Navigator.of(context).pushxxxx/pop的这个方法;）。当然希望作者尽快修复这个问题。这个bug非常致命。
