### ISSUE TITLE
Flutter 3.10.6 执行脚本文件  dart scripts/help.dart 出现‘InvalidType’类型转换错误

### ISSUE THREAD

**Issue by stdzwei** [mpflutter/mpflutter#483]
环境
 Flutter (Channel stable, 3.10.6, on macOS 13.5.1 22G90 darwin-x64, locale zh-Hans-CN)
    • Framework revision f468f3366c (3 个月前), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

dart scripts/help.dart

Crash when compiling null,
at character offset null:
type 'InvalidType' is not a subtype of type 'InterfaceType' in type cast
#0      _FfiDefinitionTransformer._generateGetterStatement (package:vm/transformations/ffi_definitions.dart:419:33)
#1      _FfiDefinitionTransformer._replaceFields (package:vm/transformations/ffi_definitions.dart:356:30)
#2      _FfiDefinitionTransformer.visitClass (package:vm/transformations/ffi_definitions.dart:135:26)
#3      Class.accept (package:kernel/ast.dart:1379:38)
#4      transformList (package:kernel/ast.dart:9648:27)
#5      Library.transformChildren (package:kernel/ast.dart:625:5)
#6      Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#7      TreeVisitor.visitLibrary (package:kernel/visitor.dart:254:35)
#8      _FfiDefinitionTransformer.visitLibrary (package:vm/transformations/ffi_definitions.dart:110:18)
#9      List.forEach (dart:core-patch/growable_array.dart:302:8)
#10     transformLibraries (package:vm/transformations/ffi_definitions.dart:81:13)
#11     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:154:9)
#12     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1129:19)
#13     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:365:7)
<asynchronous suspension>

**Comment by stdzwei** [comment]
这是全部的错误日志 

Crash when compiling null,
at character offset null:
type 'InvalidType' is not a subtype of type 'InterfaceType' in type cast
#0      _FfiDefinitionTransformer._generateGetterStatement (package:vm/transformations/ffi_definitions.dart:419:33)
#1      _FfiDefinitionTransformer._replaceFields (package:vm/transformations/ffi_definitions.dart:356:30)
#2      _FfiDefinitionTransformer.visitClass (package:vm/transformations/ffi_definitions.dart:135:26)
#3      Class.accept (package:kernel/ast.dart:1379:38)
#4      transformList (package:kernel/ast.dart:9648:27)
#5      Library.transformChildren (package:kernel/ast.dart:625:5)
#6      Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#7      TreeVisitor.visitLibrary (package:kernel/visitor.dart:254:35)
#8      _FfiDefinitionTransformer.visitLibrary (package:vm/transformations/ffi_definitions.dart:110:18)
#9      List.forEach (dart:core-patch/growable_array.dart:302:8)
#10     transformLibraries (package:vm/transformations/ffi_definitions.dart:81:13)
#11     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:154:9)
#12     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1129:19)
#13     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:365:7)
<asynchronous suspension>
#14     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#16     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:355:12)
#17     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:177:38)
<asynchronous suspension>
#18     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart)
#19     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#20     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#21     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:18)
#22     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#23     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#24     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#25     new Future.sync (dart:async/future.dart:223:31)
#26     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#27     _rootRun (dart:async/zone.dart:1190:13)
#28     _CustomZone.run (dart:async/zone.dart:1093:19)
#29     _runZoned (dart:async/zone.dart:1630:10)
#30     runZoned (dart:async/zone.dart:1550:10)
#31     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#32     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#33     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:32)
#34     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#35     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:440:17)
#36     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:208:45)
#37     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#38     _rootRun (dart:async/zone.dart:1182:47)
#39     _CustomZone.run (dart:async/zone.dart:1093:19)
#40     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#41     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#42     _rootRun (dart:async/zone.dart:1190:13)
#43     _CustomZone.run (dart:async/zone.dart:1093:19)
#44     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#45     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#46     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#47     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


#0      _FfiDefinitionTransformer._generateGetterStatement (package:vm/transformations/ffi_definitions.dart:419:33)
#1      _FfiDefinitionTransformer._replaceFields (package:vm/transformations/ffi_definitions.dart:356:30)
#2      _FfiDefinitionTransformer.visitClass (package:vm/transformations/ffi_definitions.dart:135:26)
#3      Class.accept (package:kernel/ast.dart:1379:38)
#4      transformList (package:kernel/ast.dart:9648:27)
#5      Library.transformChildren (package:kernel/ast.dart:625:5)
#6      Transformer.defaultTreeNode (package:kernel/visitor.dart:653:10)
#7      TreeVisitor.visitLibrary (package:kernel/visitor.dart:254:35)
#8      _FfiDefinitionTransformer.visitLibrary (package:vm/transformations/ffi_definitions.dart:110:18)
#9      List.forEach (dart:core-patch/growable_array.dart:302:8)
#10     transformLibraries (package:vm/transformations/ffi_definitions.dart:81:13)
#11     VmTarget.performModularTransformationsOnLibraries (package:vm/target/vm.dart:154:9)
#12     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1129:19)
#13     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:365:7)
<asynchronous suspension>
#14     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#16     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:355:12)
#17     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:177:38)
<asynchronous suspension>
#18     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart)
#19     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#20     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#21     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:18)
#22     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#23     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#24     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#25     new Future.sync (dart:async/future.dart:223:31)
#26     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#27     _rootRun (dart:async/zone.dart:1190:13)
#28     _CustomZone.run (dart:async/zone.dart:1093:19)
#29     _runZoned (dart:async/zone.dart:1630:10)
#30     runZoned (dart:async/zone.dart:1550:10)
#31     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#32     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#33     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:32)
#34     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#35     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:440:17)
#36     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:208:45)
#37     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#38     _rootRun (dart:async/zone.dart:1182:47)
#39     _CustomZone.run (dart:async/zone.dart:1093:19)
#40     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#41     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#42     _rootRun (dart:async/zone.dart:1190:13)
#43     _CustomZone.run (dart:async/zone.dart:1093:19)
#44     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#45     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#46     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#47     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
