### ISSUE TITLE
demo 工程编译Android平台，连接到手机报错：MissingPluginException(No implementation found for method ensureInitialized on channel window_manager

### ISSUE THREAD

**Issue by yanxinchen** [mpflutter/mpflutter#537]
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...
Debug service listening on ws://127.0.0.1:57940/sZrtm1XdkoQ=/ws
Syncing files to device Mi 10...
I/flutter (24932): "未连接到调试宿主"
E/flutter (24932): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method ensureInitialized on channel window_manager)
E/flutter (24932): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
E/flutter (24932): <asynchronous suspension>
E/flutter (24932): #1      WindowManager.ensureInitialized (package:window_manager/src/window_manager.dart:104:5)
E/flutter (24932): <asynchronous suspension>
E/flutter (24932): #2      runMPApp (package:mpflutter_core/mpflutter_core.dart:31:7)
E/flutter (24932): <asynchronous suspension>
E/flutter (24932): 
I/awesome_project(24932): ProcessProfilingInfo new_methods=1044 is saved saved_to_disk=1 resolve_classes_delay=8000

**Comment by yanxinchen** [comment]
解决了，需要调整一下编译参数～
![WechatIMG358](https://github.com/mpflutter/mpflutter/assets/13480869/bcd6221b-67e2-4b08-aef4-b6a47cdadcdf)
