### ISSUE TITLE
Hot Reload 报错

### ISSUE THREAD

**Issue by shitb** [mpflutter/mpflutter#565]
开发工具 IntelliJ IDEA 2023.3.2
环境: macos 14.4
flutter: 3.16.7
下载的官方模版2.5.0, 按照Hot Reload教程步骤, 运行时报错:
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ajs_interop; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:732:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:870:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:676:9)
<asynchronous suspension>
#4      starter (package:frontend_server/starter.dart:102:12)
<asynchronous suspension>
#5      main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13:14)
<asynchronous suspension>

Target kernel_snapshot failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **

Exception: Build process failed

百度了一下说:
<img width="985" alt="image" src="https://github.com/mpflutter/mpflutter/assets/4415390/392c052b-746c-4a62-9fe0-8179db5340aa">

**Comment by shitb** [comment]
完整日志:
rt:593:2: Error: Undefined name 'staticInterop'.
@staticInterop
 ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:593:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@staticInterop
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:594:2: Error: Undefined name 'anonymous'.
@anonymous
 ^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:594:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@anonymous
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:604:2: Error: Couldn't find constructor 'JS'.
@JS('OverconstrainedError')
 ^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:605:2: Error: Undefined name 'staticInterop'.
@staticInterop
 ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:605:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@staticInterop
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:617:2: Error: Couldn't find constructor 'JS'.
@JS('MediaDevices')
 ^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:618:2: Error: Undefined name 'staticInterop'.
@staticInterop
 ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:618:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@staticInterop
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:637:2: Error: Couldn't find constructor 'JS'.
@JS('MediaDeviceInfo')
 ^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:638:2: Error: Undefined name 'staticInterop'.
@staticInterop
 ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:638:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@staticInterop
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:649:2: Error: Couldn't find constructor 'JS'.
@JS('InputDeviceInfo')
 ^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:650:2: Error: Undefined name 'staticInterop'.
@staticInterop
 ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:650:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@staticInterop
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:657:2: Error: Couldn't find constructor 'JS'.
@JS()
 ^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:658:2: Error: Undefined name 'staticInterop'.
@staticInterop
 ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:658:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@staticInterop
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:659:2: Error: Undefined name 'anonymous'.
@anonymous
 ^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:659:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@anonymous
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:680:2: Error: Couldn't find constructor 'JS'.
@JS()
 ^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:681:2: Error: Undefined name 'staticInterop'.
@staticInterop
 ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:681:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@staticInterop
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:682:2: Error: Undefined name 'anonymous'.
@anonymous
 ^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:682:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@anonymous
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:697:2: Error: Couldn't find constructor 'JS'.
@JS()
 ^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:698:2: Error: Undefined name 'staticInterop'.
@staticInterop
 ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:698:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@staticInterop
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:699:2: Error: Undefined name 'anonymous'.
@anonymous
 ^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:699:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@anonymous
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:714:2: Error: Couldn't find constructor 'JS'.
@JS()
 ^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:715:2: Error: Undefined name 'staticInterop'.
@staticInterop
 ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:715:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@staticInterop
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:716:2: Error: Undefined name 'anonymous'.
@anonymous
 ^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:716:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@anonymous
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:731:2: Error: Couldn't find constructor 'JS'.
@JS()
 ^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:732:2: Error: Undefined name 'staticInterop'.
@staticInterop
 ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:732:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@staticInterop
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:733:2: Error: Undefined name 'anonymous'.
@anonymous
 ^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:733:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@anonymous
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:748:2: Error: Couldn't find constructor 'JS'.
@JS()
 ^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:749:2: Error: Undefined name 'staticInterop'.
@staticInterop
 ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:749:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@staticInterop
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:750:2: Error: Undefined name 'anonymous'.
@anonymous
 ^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:750:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@anonymous
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:765:2: Error: Couldn't find constructor 'JS'.
@JS()
 ^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:766:2: Error: Undefined name 'staticInterop'.
@staticInterop
 ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:766:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@staticInterop
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:767:2: Error: Undefined name 'anonymous'.
@anonymous
 ^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:767:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@anonymous
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:783:2: Error: Couldn't find constructor 'JS'.
@JS()
 ^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:784:2: Error: Undefined name 'staticInterop'.
@staticInterop
 ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:784:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@staticInterop
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:785:2: Error: Undefined name 'anonymous'.
@anonymous
 ^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_streams.dart:785:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@anonymous
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_transform.dart:10:2: Error: Couldn't find constructor 'JS'.
@JS('MediaStreamTrackProcessor')
 ^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_transform.dart:11:2: Error: Undefined name 'staticInterop'.
@staticInterop
 ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_transform.dart:11:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@staticInterop
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_transform.dart:22:2: Error: Couldn't find constructor 'JS'.
@JS()
 ^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_transform.dart:23:2: Error: Undefined name 'staticInterop'.
@staticInterop
 ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_transform.dart:23:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@staticInterop
 ^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/mediacapture_transform.dart:24:2: Error: Undefined name 'anonymous'.

../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc.dart:641:33: Error: 'JSArray' isn't a type.
  external set headerExtensions(JSArray value);
                                ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc.dart:725:39: Error: 'JSArray' isn't a type.
  external JSVoid setCodecPreferences(JSArray codecs);
                                      ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc.dart:860:5: Error: 'JSArray' isn't a type.
    JSArray streams,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc.dart:870:24: Error: 'JSArray' isn't a type.
  external set streams(JSArray value);
                       ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc.dart:895:24: Error: 'JSAny' isn't a type.
  external JSVoid send(JSAny? data);
                       ^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc_encoded_transform.dart:67:14: Error: 'JSAny' isn't a type.
    required JSAny? frame,
             ^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc_encoded_transform.dart:76:22: Error: 'JSAny' isn't a type.
  external set frame(JSAny? value);
                     ^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc_encoded_transform.dart:88:5: Error: 'JSArray' isn't a type.
    JSArray dependencies,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc_encoded_transform.dart:95:5: Error: 'JSArray' isn't a type.
    JSArray contributingSources,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc_encoded_transform.dart:105:29: Error: 'JSArray' isn't a type.
  external set dependencies(JSArray value);
                            ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc_encoded_transform.dart:119:36: Error: 'JSArray' isn't a type.
  external set contributingSources(JSArray value);
                                   ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc_encoded_transform.dart:134:21: Error: 'JSArrayBuffer' isn't a type.
  external set data(JSArrayBuffer value);
                    ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc_encoded_transform.dart:145:5: Error: 'JSArray' isn't a type.
    JSArray contributingSources,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc_encoded_transform.dart:157:36: Error: 'JSArray' isn't a type.
  external set contributingSources(JSArray value);
                                   ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc_encoded_transform.dart:171:21: Error: 'JSArrayBuffer' isn't a type.
  external set data(JSArrayBuffer value);
                    ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc_encoded_transform.dart:200:5: Error: 'JSAny' isn't a type.
    JSAny? options,
    ^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc_encoded_transform.dart:201:5: Error: 'JSArray' isn't a type.
    JSArray transfer,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc_ice.dart:15:5: Error: 'JSArray' isn't a type.
    JSArray iceServers,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc_ice.dart:22:27: Error: 'JSArray' isn't a type.
  external set iceServers(JSArray value);
                          ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc_stats.dart:327:5: Error: 'JSAny' isn't a type.
    JSAny? qualityLimitationDurations,
    ^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webrtc_stats.dart:382:43: Error: 'JSAny' isn't a type.
  external set qualityLimitationDurations(JSAny? value);
                                          ^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/websockets.dart:17:5: Error: 'JSAny' isn't a type.
    JSAny? protocols,
    ^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/websockets.dart:31:24: Error: 'JSAny' isn't a type.
  external JSVoid send(JSAny? data);
                       ^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webtransport.dart:84:5: Error: 'JSArray' isn't a type.
    JSArray serverCertificateHashes,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webtransport.dart:94:40: Error: 'JSArray' isn't a type.
  external set serverCertificateHashes(JSArray value);
                                       ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:52:14: Error: 'JSArray' isn't a type.
    required JSArray filters,
             ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:53:5: Error: 'JSArray' isn't a type.
    JSArray exclusionFilters,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:58:24: Error: 'JSArray' isn't a type.
  external set filters(JSArray value);
                       ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:60:33: Error: 'JSArray' isn't a type.
  external set exclusionFilters(JSArray value);
                                ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:107:5: Error: 'JSDataView' isn't a type.
    JSDataView? data,
    ^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:135:5: Error: 'JSDataView' isn't a type.
    JSDataView? data,
    ^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:149:5: Error: 'JSArray' isn't a type.
    JSArray packets, [
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:150:5: Error: 'JSDataView' isn't a type.
    JSDataView? data,
    ^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:178:52: Error: 'JSArray' isn't a type.
  external factory USBIsochronousOutTransferResult(JSArray packets);
                                                   ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:223:5: Error: 'JSArray' isn't a type.
    JSArray packetLengths,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:228:5: Error: 'JSArray' isn't a type.
    JSArray packetLengths,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:348:5: Error: 'JSArray' isn't a type.
    JSArray filters,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:349:5: Error: 'JSArray' isn't a type.
    JSArray exclusionFilters,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:354:24: Error: 'JSArray' isn't a type.
  external set filters(JSArray value);
                       ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:356:33: Error: 'JSArray' isn't a type.
  external set exclusionFilters(JSArray value);
                                ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:384:42: Error: 'JSArray' isn't a type.
  external factory USBPermissionStorage({JSArray allowedDevices});
                                         ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:388:31: Error: 'JSArray' isn't a type.
  external set allowedDevices(JSArray value);
                              ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webusb.dart:397:24: Error: 'JSArray' isn't a type.
  external set devices(JSArray value);
                       ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:54:5: Error: 'JSArray' isn't a type.
    JSArray requiredFeatures,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:55:5: Error: 'JSArray' isn't a type.
    JSArray optionalFeatures,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:64:33: Error: 'JSArray' isn't a type.
  external set requiredFeatures(JSArray value);
                                ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:66:33: Error: 'JSArray' isn't a type.
  external set optionalFeatures(JSArray value);
                                ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:132:5: Error: 'JSArray' isn't a type.
    JSArray? layers,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:145:23: Error: 'JSArray' isn't a type.
  external set layers(JSArray? value);
                      ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:176:5: Error: 'JSArray' isn't a type.
    JSArray jointSpaces,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:177:5: Error: 'JSFloat32Array' isn't a type.
    JSFloat32Array radii,
    ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:180:5: Error: 'JSArray' isn't a type.
    JSArray spaces,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:182:5: Error: 'JSFloat32Array' isn't a type.
    JSFloat32Array transforms,
    ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:437:14: Error: 'JSArray' isn't a type.
    required JSArray added,
             ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:438:14: Error: 'JSArray' isn't a type.
    required JSArray removed,
             ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:446:22: Error: 'JSArray' isn't a type.
  external set added(JSArray value);
                     ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:448:24: Error: 'JSArray' isn't a type.
  external set removed(JSArray value);
                       ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:502:5: Error: 'JSArray' isn't a type.
    JSArray requiredFeatures,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:503:5: Error: 'JSArray' isn't a type.
    JSArray optionalFeatures,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:510:33: Error: 'JSArray' isn't a type.
  external set requiredFeatures(JSArray value);
                                ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:512:33: Error: 'JSArray' isn't a type.
  external set optionalFeatures(JSArray value);
                                ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr.dart:521:24: Error: 'JSArray' isn't a type.
  external set granted(JSArray value);
                       ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr_depth_sensing.dart:18:14: Error: 'JSArray' isn't a type.
    required JSArray usagePreference,
             ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr_depth_sensing.dart:19:14: Error: 'JSArray' isn't a type.
    required JSArray dataFormatPreference,
             ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr_depth_sensing.dart:24:32: Error: 'JSArray' isn't a type.
  external set usagePreference(JSArray value);
                               ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr_depth_sensing.dart:26:37: Error: 'JSArray' isn't a type.
  external set dataFormatPreference(JSArray value);
                                    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr_hit_test.dart:18:5: Error: 'JSArray' isn't a type.
    JSArray entityTypes,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr_hit_test.dart:26:28: Error: 'JSArray' isn't a type.
  external set entityTypes(JSArray value);
                           ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr_hit_test.dart:38:5: Error: 'JSArray' isn't a type.
    JSArray entityTypes,
    ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr_hit_test.dart:47:28: Error: 'JSArray' isn't a type.
  external set entityTypes(JSArray value);
                           ^^^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/webxr_hit_test.dart:116:5: Error: 'JSAny' isn't a type.
    JSAny? originOrTransform,
    ^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/xhr.dart:67:25: Error: 'JSAny' isn't a type.
  external JSVoid send([JSAny? body]);
                        ^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/xhr.dart:102:5: Error: 'JSAny' isn't a type.
    JSAny? blobValueOrValue, [
    ^^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/web-0.3.0/lib/src/dom/xhr.dart:111:5: Error: 'JSAny' isn't a type.
    JSAny? blobValueOrValue, [
    ^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ajs_interop; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:732:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:870:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:676:9)
<asynchronous suspension>
#4      starter (package:frontend_server/starter.dart:102:12)
<asynchronous suspension>
#5      main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13:14)
<asynchronous suspension>

Target kernel_snapshot failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **

Exception: Build process failed

**Comment by shitb** [comment]
解决了:
1. 删除 pubspec.lock
2. 重新 flutter pub get
