### ISSUE TITLE
开发模拟器能出来，但是打包之后就报错导致页面加载不出来  

### ISSUE THREAD

**Issue by hhhero** [mpflutter/mpflutter#614]
`
[jsbridge] invoke accessSync fail: too eayly. Error: invoke too eayly
    at https://lib/WAServiceMainContext.js:1:113702
    at Object.invoke (https://lib/WAServiceMainContext.js:1:111205)
    at r (https://lib/WAServiceMainContext.js:1:339489)
    at be.tryInitializeWeUIStyleSheets (https://lib/WAServiceMainContext.js:1:356056)
    at https://lib/WAServiceMainContext.js:1:355925
    at Array.forEach (<anonymous>)
    at https://lib/WAServiceMainContext.js:1:355697
    at Object.batchUpdate (https://lib/WARenderContext.js:1:1280932)
    at https://lib/WAServiceMainContext.js:1:355677
    at https://lib/WAServiceMainContext.js:1:342541
`

**Comment by ggdream** [comment]
@hhhero 请问是怎么解决的？
